server:
  port: 5001
  
spring:  application:    name: CLOUD-CONFIG-SERVER
  cloud:    config:      server:        git:          uri: https://github.com/maheshgt/config-server
          clone-on-start: true  
